---

image: gcc

build_Linux:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux
build_linux_unsecured_with_rd:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_unsecured_with_rd
.build_linux_unsecured:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_unsecured
build_linux_secured:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_secured
build_linux_secured_with_rd:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_secured_with_rd
build_linux_unsecured_with_mq:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_unsecured_with_mq
.build_linux_unsecured_with_tcp:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_unsecured_with_tcp
build_linux_secured_with_tcp:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_secured_with_tcp
build_linux_full:
    stage: build
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath
        - set -o pipefail
        - export VERBOSE=false
        - export CCACHE_DISABLE=false
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
        - ./auto_build.sh linux_full
.Android_build:
    stage: build
    image: openjdk:8-jdk
    before_script:
        - apt update && apt -y install build-essential git scons libtool autoconf valgrind doxygen wget unzip cmake libboost-dev libboost-program-options-dev libboost-thread-dev uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev chrpath lib32stdc++6 lib32z1 swig
        - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        - unzip -d android-sdk-linux android-sdk.zip
        - echo y | android-sdk-linux/tools/bin/sdkmanager "ndk-bundle" >/dev/null
        - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-28" >/dev/null
        - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
        - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;28.0.2" >/dev/null
        - export ANDROID_HOME=$PWD/android-sdk-linux
        - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
        # temporarily disable checking for EPIPE error and use yes to accept all licenses
        - set +o pipefail
        - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
        - set -o pipefail
        - ./android-sdk-linux/ndk-bundle/build/tools/make_standalone_toolchain.py --arch arm --api 23 --install-dir ~/android-arm-23
        - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
        - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2
    script:
      - ./auto_build.sh android_secured
